[package]
name = "rusty_gains"
version = "0.1.0"
authors = ["Philip Trauth <trauthp@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.26"
crossterm = "0.26.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
ratatui = "0.21.0"